services:
    oro_paypal_express.method.generator.identifier:
        parent: oro_integration.generator.prefixed_identifier_generator
        public: true
        arguments:
            - 'oro_paypal_express'

    oro_paypal_express.method.config.factory:
        class: Oro\Bundle\PayPalExpressBundle\Method\Config\PayPalExpressConfigFactory
        arguments:
            - '@oro_paypal_express.method.generator.identifier'
            - '@oro_locale.helper.localization'
            - '@oro_security.encoder.mcrypt'

    oro_paypal_express.method.config.provider:
        class: Oro\Bundle\PayPalExpressBundle\Method\Config\PayPalExpressConfigProvider
        arguments:
            - '@doctrine'
            - '@logger'
            - '@oro_paypal_express.method.config.factory'

    oro_paypal_express.method.view.factory:
        class: Oro\Bundle\PayPalExpressBundle\Method\View\PayPalViewFactory

    oro_paypal_express.method.view.provider:
        class: Oro\Bundle\PayPalExpressBundle\Method\View\PayPalViewProvider
        arguments:
            - '@oro_paypal_express.method.view.factory'
            - '@oro_paypal_express.method.config.provider'

    oro_paypal_express.method.translator.line_item:
        class: Oro\Bundle\PayPalExpressBundle\Method\Translator\LineItemTranslator

    oro_paypal_express.method.translator.method_config:
        class: Oro\Bundle\PayPalExpressBundle\Method\Translator\MethodConfigTranslator

    oro_paypal_express.method.translator.payment_transaction:
        class: Oro\Bundle\PayPalExpressBundle\Method\Translator\PaymentTransactionTranslator
        arguments:
            - '@oro_paypal_express.pay_pal.helper.supported_currencies'
            - '@oro_paypal_express.method.translator.line_item'
            - '@oro_entity.doctrine_helper'
            - '@oro_paypal_express.pay_pal.provider.tax'

    oro_paypal_express.method.paypal_transport_facade:
        class: Oro\Bundle\PayPalExpressBundle\Method\PayPalTransportFacade
        arguments:
            - '@oro_paypal_express.pay_pal.transport'
            - '@oro_paypal_express.method.translator.payment_transaction'
            - '@oro_paypal_express.method.translator.method_config'
