services:
    oro_paypal_express.pay_pal.helper.supported_currencies:
        class: Oro\Bundle\PayPalExpressBundle\Transport\SupportedCurrenciesHelper

    oro_paypal_express.pay_pal.provider.tax:
        class: Oro\Bundle\PayPalExpressBundle\Provider\TaxProvider
        arguments:
            - '@oro_tax.manager.tax_manager'
            - '@logger'

    oro_paypal_express.pay_pal.translator.sdk_object:
        class: Oro\Bundle\PayPalExpressBundle\Transport\PayPalSDKObjectTranslator

    oro_paypal_express.pay_pal.client:
        class: Oro\Bundle\PayPalExpressBundle\Transport\PayPalClient

    oro_paypal_express.pay_pal.transport:
        class: Oro\Bundle\PayPalExpressBundle\Transport\PayPalTransport
        arguments:
            - '@oro_paypal_express.pay_pal.translator.sdk_object'
            - '@oro_paypal_express.pay_pal.client'
            - '@logger'
